# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run imov
      run: |
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        sudo echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        sudo echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        sudo source ~/.bashrc
        # 注意，文件名不一定叫.bash_profile，有可能是.bashrc
        pyenv install 3.6.0
        sudo pyenv global 3.6.0
        pip install setuptools
        pip install imov
        imov
